version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sportstock-db
    restart: unless-stopped
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: sportstock
      POSTGRES_USER: sportstock
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localdev}
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro


volumes:
  postgres-data: