spring:
  application:
    name: stock-market
  config:
    import: optional:file:.env[.properties],optional:file:../../.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:6432}/sportstock?currentSchema=market
    username: ${DB_USERNAME:sportstock}
    password: ${DB_PASSWORD:localdev}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: market
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: market

server:
  port: ${SERVER_PORT:8082}
