spring.application.name=portfolio-application

server.port=${USER_AUTH_PORT:8130}

# --- JWT Secret Key ---
jwt.secret=${JWT_SECRET_KEY}

spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]
# --- PostgreSQL connection ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:6432}/${DB_NAME:sportstock}?currentSchema=portfolio
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=portfolio

spring.flyway.enabled=true
spring.flyway.schemas=portfolio
spring.flyway.locations=classpath:db/migration
spring.flyway.create-schemas=true