CREATE SCHEMA IF NOT EXISTS ingestion;
CREATE SCHEMA IF NOT EXISTS market;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS league;

GRANT ALL ON SCHEMA ingestion TO sportstock;
GRANT ALL ON SCHEMA market TO sportstock;
GRANT ALL ON SCHEMA users TO sportstock;
GRANT ALL ON SCHEMA league TO sportstock;